#!/usr/bin/env python3
"""Render a set of katakana glyphs to 8x8 1-bit bitmaps and emit a C header.

Used for the Matrix "digital rain". Output: include/matrix_glyphs.h with
  #define MTX_GLYPH_N <n>
  const uint8_t mtxGlyphs[MTX_GLYPH_N][8] = { ... };
Each glyph is 8 rows; bit 7 (0x80) is the leftmost pixel (TFT_eSPI drawBitmap).
"""
import sys
from PIL import Image, ImageFont, ImageDraw

FONT = "/System/Library/Fonts/AquaKana.ttc"
SIZE = 9            # render size; katakana fills an 8x8 cell well around here
W = H = 8

# Katakana (full-width) — the iconic Matrix glyphs. A spread across the block.
chars = [chr(c) for c in range(0x30A2, 0x30F4)]
# drop a few that render nearly blank / too sparse at this size
chars = [c for c in chars if c not in "ッャュョヮ"]

def render(ch, font):
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    # center the glyph in the cell
    try:
        bb = d.textbbox((0, 0), ch, font=font)
        gw, gh = bb[2] - bb[0], bb[3] - bb[1]
        ox, oy = (W - gw) // 2 - bb[0], (H - gh) // 2 - bb[1]
    except Exception:
        ox = oy = 0
    d.text((ox, oy), ch, fill=255, font=font)
    return img

def to_bytes(img):
    rows = []
    for y in range(H):
        b = 0
        for x in range(W):
            if img.getpixel((x, y)) > 110:
                b |= (0x80 >> x)
        rows.append(b)
    return rows

def main():
    font = ImageFont.truetype(FONT, SIZE)
    glyphs = []
    for ch in chars:
        rows = to_bytes(render(ch, font))
        if sum(bin(r).count("1") for r in rows) >= 6:   # skip near-empty
            glyphs.append(rows)
    out = ["// Generated by assets/gen_matrix_glyphs.py — katakana 8x8 1-bit.",
           "#pragma once", "#include <Arduino.h>", "",
           f"#define MTX_GLYPH_N {len(glyphs)}", "",
           "const uint8_t mtxGlyphs[MTX_GLYPH_N][8] = {"]
    for g in glyphs:
        out.append("  {" + ", ".join(f"0x{b:02X}" for b in g) + "},")
    out.append("};")
    text = "\n".join(out) + "\n"
    with open("include/matrix_glyphs.h", "w") as f:
        f.write(text)
    print(f"wrote include/matrix_glyphs.h with {len(glyphs)} glyphs")

if __name__ == "__main__":
    main()
